services:
  # Your existing services
  web:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

  db:
    image: postgres:15
    container_name: fastapi-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Airflow services
  airflow-webserver:
    image: apache/airflow:2.7.1
    container_name: airflow-webserver
    user: root
    command: >
      bash -c "
        pip install pandas psycopg2-binary python-dotenv sqlalchemy &&
        airflow webserver
      "
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
      - ./models.py:/opt/airflow/models.py
      - ./database.py:/opt/airflow/database.py
      - ./.env:/opt/airflow/.env
      - ./requirements.txt:/opt/airflow/requirements.txt
    depends_on:
      - db
      - airflow-init

  airflow-scheduler:
    image: apache/airflow:2.7.1
    container_name: airflow-scheduler
    user: root
    command: >
      bash -c "
        pip install pandas psycopg2-binary python-dotenv sqlalchemy &&
        airflow scheduler
      "
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
      - ./models.py:/opt/airflow/models.py
      - ./database.py:/opt/airflow/database.py
      - ./.env:/opt/airflow/.env
      - ./requirements.txt:/opt/airflow/requirements.txt
    depends_on:
      - db
      - airflow-init

  airflow-init:
    image: apache/airflow:2.7.1
    container_name: airflow-init
    user: root
    command: >
      bash -c "
        pip install pandas psycopg2-binary python-dotenv sqlalchemy &&
        airflow db init &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com
      "
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/airflow
    depends_on:
      - db
    restart: "no"

volumes:
  postgres_data: