version: '3.9'

services:
  web:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./raw:/app/data/raw
      - ./processed:/app/data/processed

  db:
    image: postgres:15
    container_name: fastapi-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

volumes:
  postgres_data:

